# Gitleaks 설정 파일
# KRA 프로젝트에 맞춤 설정

# 전역 허용 목록 (false positive 완화)
[allowlist]
paths = [
  "KRA_PUBLIC_API_GUIDE.md",
  "docs/.*\\.md",
  "apps/api/tests/.*",
  "apps/collector/src/middleware/README\\.md",
  "apps/collector/.env\\.example",
  "apps/collector/.env\\.test"
]
regexes = [
  # 일반적인 환경변수 접근 패턴 허용
  "process\\.env\\.",
  "os\\.getenv",
  "import\\.meta\\.env",
  "VITE_.*",
  "dotenv",
  # 테스트 인자명(x_api_key=...) 허용
  "^\s*x_api_key\s*=.*"
]

# 커스텀 룰 추가
[[rules]]
id = "kra-api-key"
description = "KRA API serviceKey 하드코딩 감지"
regex = '''serviceKey\s*[:=]\s*["']?[a-zA-Z0-9+/=]{20,}["']?'''
tags = ["api", "key", "kra"]

[[rules]]
id = "env-file"
description = ".env 파일 내용 감지"
# 단어 경계와 라인 시작을 고려하여 코드 인자(x_api_key=...)는 제외
regex = '''(?im)^\s*\b(KRA_API_KEY|SERVICE_KEY|API_KEY)\s*=\s*.+$'''
tags = ["env", "config"]
