"""출전표 확정 시점 필드 메타데이터 저장 계약과 중앙 규칙 레지스트리.

필드 카탈로그 본문은 사람이 읽기 좋은 기준 문서다. 이 모듈은 동일 내용을
CSV 한 행 단위로 저장할 때 필요한 스키마, 열 순서, enum 제약을 코드로 고정한다.

또한 "출전표 확정 전/후 공개 여부"를 판정하는 최소 운영 규칙 집합을
중앙 상수로 제공해 수집·적재·학습 파이프라인이 같은 기준을 재사용하게 한다.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

METADATA_SCHEMA_VERSION = "prerace-field-metadata-v1"
CANONICAL_STORAGE_RELATIVE_PATH = Path("data/contracts/prerace_field_metadata_v1.csv")
CANONICAL_STORAGE_FORMAT = "csv"
CANONICAL_STORAGE_ENCODING = "utf-8"
MULTI_VALUE_CELL_ENCODING = "json-array"
ROW_PRIMARY_KEY: tuple[str, ...] = ("field_path",)
DEFAULT_RULE_OWNER = "shared.prerace_field_metadata_schema"

FIELD_ROLES: tuple[str, ...] = (
    "source",
    "derived",
    "metadata",
    "label",
)

AVAILABILITY_STAGES: tuple[str, ...] = (
    "L-1",
    "L0",
    "L0 snapshot",
    "?",
    "L+1",
)

VALIDATION_STATUSES: tuple[str, ...] = (
    "documented",
    "measured",
    "pending_measurement",
    "rejected",
)

OPERATIONAL_STATUSES: tuple[str, ...] = (
    "필수",
    "선택",
    "보류",
    "금지",
    "라벨 전용",
    "메타 전용",
    "허용",
    "조건부 허용",
)

TRAIN_INFERENCE_FLAGS: tuple[str, ...] = (
    "ALLOW",
    "ALLOW_SNAPSHOT_ONLY",
    "ALLOW_STORED_ONLY",
    "HOLD",
    "BLOCK",
    "LABEL_ONLY",
    "META_ONLY",
)

RULE_MATCH_TYPES: tuple[str, ...] = (
    "exact",
    "prefix",
    "leaf",
)

_PATH_INDEX_PATTERN = re.compile(r"\[\d+\]")


@dataclass(frozen=True, slots=True)
class MetadataColumnSpec:
    """필드 메타데이터 CSV의 단일 컬럼 정의."""

    name: str
    required: bool
    description: str


COLUMN_SPECS: tuple[MetadataColumnSpec, ...] = (
    MetadataColumnSpec(
        name="metadata_schema_version",
        required=True,
        description="메타데이터 행이 따르는 저장 계약 버전. 현재 값은 prerace-field-metadata-v1.",
    ),
    MetadataColumnSpec(
        name="field_path",
        required=True,
        description="표준 필드 카탈로그 기준 경로. 예: horses[].training, track.weather.",
    ),
    MetadataColumnSpec(
        name="field_role",
        required=True,
        description="source/derived/metadata/label 중 하나. 필드 성격을 고정한다.",
    ),
    MetadataColumnSpec(
        name="source_api",
        required=True,
        description="원천 API 이름 또는 INTERNAL. derived/metadata/label 필드는 INTERNAL 사용.",
    ),
    MetadataColumnSpec(
        name="source_field",
        required=True,
        description="원천 raw field 또는 내부 파생 기준식 이름. 배열 블록은 * 또는 item[] 표기 허용.",
    ),
    MetadataColumnSpec(
        name="availability_stage",
        required=True,
        description="최초 가용 시점. L-1, L0, L0 snapshot, ?, L+1 중 하나.",
    ),
    MetadataColumnSpec(
        name="publication_basis",
        required=True,
        description="공개 근거의 짧은 요약. 예: 공식 엔드포인트 문서, 런타임 수집 경로, 결과 수집 경로.",
    ),
    MetadataColumnSpec(
        name="publication_basis_refs",
        required=True,
        description="공개 근거 파일/문서 참조 목록. 여러 값은 JSON array 문자열로 저장한다.",
    ),
    MetadataColumnSpec(
        name="exception_rule",
        required=True,
        description="snapshot 고정, 재조회 금지, soft-fail 등 예외 조건 요약.",
    ),
    MetadataColumnSpec(
        name="validation_status",
        required=True,
        description="documented, measured, pending_measurement, rejected 중 하나.",
    ),
    MetadataColumnSpec(
        name="validation_evidence",
        required=True,
        description="검증 근거 요약 또는 로그/문서 참조 목록. 여러 값은 JSON array 문자열 허용.",
    ),
    MetadataColumnSpec(
        name="operational_status",
        required=True,
        description="필수/선택/보류/금지/라벨 전용/메타 전용/허용/조건부 허용 중 하나.",
    ),
    MetadataColumnSpec(
        name="train_inference_flag",
        required=True,
        description=(
            "학습/추론 공통 판정 플래그. "
            "ALLOW/ALLOW_SNAPSHOT_ONLY/ALLOW_STORED_ONLY/HOLD/"
            "BLOCK/LABEL_ONLY/META_ONLY 중 하나."
        ),
    ),
    MetadataColumnSpec(
        name="join_key",
        required=False,
        description="원천 row를 결합할 때 사용하는 조인 키. 없으면 빈 문자열.",
    ),
    MetadataColumnSpec(
        name="value_type",
        required=False,
        description="scalar/object/array/mixed 등 값 형태 메모.",
    ),
    MetadataColumnSpec(
        name="mutable_after_publish",
        required=False,
        description="불변/가변/재조회 의존/사후 전용 등 갱신 특성.",
    ),
    MetadataColumnSpec(
        name="owner",
        required=False,
        description="담당자나 관리 모듈 식별자.",
    ),
    MetadataColumnSpec(
        name="last_verified_at",
        required=False,
        description="마지막 검증 시각 ISO-8601. 미검증이면 빈 문자열.",
    ),
    MetadataColumnSpec(
        name="notes",
        required=False,
        description="기타 보충 메모.",
    ),
)

REQUIRED_COLUMNS: tuple[str, ...] = tuple(
    column.name for column in COLUMN_SPECS if column.required
)
OPTIONAL_COLUMNS: tuple[str, ...] = tuple(
    column.name for column in COLUMN_SPECS if not column.required
)
ALL_COLUMNS: tuple[str, ...] = tuple(column.name for column in COLUMN_SPECS)


def csv_header() -> str:
    """정규 CSV 헤더 문자열을 반환한다."""

    return ",".join(ALL_COLUMNS)


@dataclass(frozen=True, slots=True)
class FieldMetadataRule:
    """출전표 확정 시점 필드 메타데이터 규칙 한 행.

    `field_path` 는 CSV/문서 기준 canonical path 이다.
    `match_type` 은 런타임 payload 경로를 어떤 방식으로 이 규칙에 매칭할지 정한다.
    """

    field_path: str
    field_role: str
    source_api: str
    source_field: str
    availability_stage: str
    publication_basis: str
    publication_basis_refs: tuple[str, ...]
    exception_rule: str
    validation_status: str
    validation_evidence: tuple[str, ...]
    operational_status: str
    train_inference_flag: str
    match_type: str = "exact"
    path_aliases: tuple[str, ...] = ()
    join_key: str = ""
    value_type: str = ""
    mutable_after_publish: str = ""
    owner: str = DEFAULT_RULE_OWNER
    last_verified_at: str = ""
    notes: str = ""

    def __post_init__(self) -> None:
        if self.field_role not in FIELD_ROLES:
            raise ValueError(f"unsupported field_role: {self.field_role}")
        if self.availability_stage not in AVAILABILITY_STAGES:
            raise ValueError(
                f"unsupported availability_stage: {self.availability_stage}"
            )
        if self.validation_status not in VALIDATION_STATUSES:
            raise ValueError(f"unsupported validation_status: {self.validation_status}")
        if self.operational_status not in OPERATIONAL_STATUSES:
            raise ValueError(
                f"unsupported operational_status: {self.operational_status}"
            )
        if self.train_inference_flag not in TRAIN_INFERENCE_FLAGS:
            raise ValueError(
                f"unsupported train_inference_flag: {self.train_inference_flag}"
            )
        if self.match_type not in RULE_MATCH_TYPES:
            raise ValueError(f"unsupported match_type: {self.match_type}")

    def normalized_patterns(self) -> tuple[str, ...]:
        return tuple(
            normalize_field_path(path) for path in (self.field_path, *self.path_aliases)
        )

    def to_csv_row(self) -> dict[str, str]:
        return {
            "metadata_schema_version": METADATA_SCHEMA_VERSION,
            "field_path": self.field_path,
            "field_role": self.field_role,
            "source_api": self.source_api,
            "source_field": self.source_field,
            "availability_stage": self.availability_stage,
            "publication_basis": self.publication_basis,
            "publication_basis_refs": _encode_multi_value(self.publication_basis_refs),
            "exception_rule": self.exception_rule,
            "validation_status": self.validation_status,
            "validation_evidence": _encode_multi_value(self.validation_evidence),
            "operational_status": self.operational_status,
            "train_inference_flag": self.train_inference_flag,
            "join_key": self.join_key,
            "value_type": self.value_type,
            "mutable_after_publish": self.mutable_after_publish,
            "owner": self.owner,
            "last_verified_at": self.last_verified_at,
            "notes": self.notes,
        }


def normalize_field_path(path: str) -> str:
    """배열 인덱스를 제거한 canonical field path를 반환한다."""

    return _PATH_INDEX_PATTERN.sub("[]", path)


def _encode_multi_value(values: tuple[str, ...]) -> str:
    return json.dumps(list(values), ensure_ascii=False)


def _rule(
    *,
    field_path: str,
    field_role: str,
    source_api: str,
    source_field: str,
    availability_stage: str,
    publication_basis: str,
    publication_basis_refs: tuple[str, ...],
    exception_rule: str,
    validation_status: str,
    validation_evidence: tuple[str, ...],
    operational_status: str,
    train_inference_flag: str,
    match_type: str = "exact",
    path_aliases: tuple[str, ...] = (),
    join_key: str = "",
    value_type: str = "",
    mutable_after_publish: str = "",
    notes: str = "",
) -> FieldMetadataRule:
    return FieldMetadataRule(
        field_path=field_path,
        field_role=field_role,
        source_api=source_api,
        source_field=source_field,
        availability_stage=availability_stage,
        publication_basis=publication_basis,
        publication_basis_refs=publication_basis_refs,
        exception_rule=exception_rule,
        validation_status=validation_status,
        validation_evidence=validation_evidence,
        operational_status=operational_status,
        train_inference_flag=train_inference_flag,
        match_type=match_type,
        path_aliases=path_aliases,
        join_key=join_key,
        value_type=value_type,
        mutable_after_publish=mutable_after_publish,
        notes=notes,
    )


_RULEBOOK_REF = (
    "docs/prerace-field-availability-judgment-rules.md",
    "docs/prerace-field-metadata-schema.md",
)
_KRA_COLLECTION_REFS = (
    "apps/api/services/kra_api_service.py",
    "apps/api/services/collection_service.py",
    "apps/api/services/race_processing_workflow.py",
)
_POST_RACE_REFS = (
    "apps/api/services/result_collection_service.py",
    "packages/scripts/evaluation/leakage_checks.py",
)
_HOLDOUT_REFS = (
    "docs/holdout-entry-finalization-rule.md",
    "docs/kra-race-lifecycle-timing-matrix.md",
)
_FEATURE_REFS = (
    "packages/scripts/feature_engineering.py",
    "packages/scripts/shared/db_client.py",
)
_SOURCE_SCHEMA_REFS = (
    "packages/scripts/shared/prerace_source_schema.py",
    "docs/prerace-standard-field-catalog.md",
)
_ENTRY_CARD_REFS = (
    *_KRA_COLLECTION_REFS,
    "docs/prerace-standard-field-catalog.md",
)

EXACT_STANDARD_FIELD_RULES: tuple[FieldMetadataRule, ...] = (
    _rule(
        field_path="schema_version",
        field_role="derived",
        source_api="INTERNAL",
        source_field="SCHEMA_VERSION",
        availability_stage="L0",
        publication_basis="출전표 확정 시점 공통 스키마 버전을 payload와 함께 고정한다",
        publication_basis_refs=_SOURCE_SCHEMA_REFS,
        exception_rule="스키마 버전 문자열은 snapshot 생성 시점 값을 그대로 유지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="불변",
    ),
    _rule(
        field_path="race_date",
        field_role="source",
        source_api="API214_1",
        source_field="rcDate",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 경주일을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="모든 item에서 동일한 값이어야 하며 YYYYMMDD 문자열로 정규화",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_no",
        field_role="source",
        source_api="API214_1",
        source_field="rcNo",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 경주번호를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="정수 경주번호로 정규화해 저장",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="meet",
        field_role="source",
        source_api="API214_1",
        source_field="meet",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 개최지 코드를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="서울/제주/부경 alias를 1/2/3 meet 코드로 정규화",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="date",
        field_role="derived",
        source_api="INTERNAL",
        source_field="race_date",
        availability_stage="L0",
        publication_basis="하위 호환을 위해 race_date를 date alias로 함께 저장한다",
        publication_basis_refs=_SOURCE_SCHEMA_REFS,
        exception_rule="race_date와 동일한 값을 유지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="불변",
    ),
    _rule(
        field_path="race_number",
        field_role="derived",
        source_api="INTERNAL",
        source_field="race_no",
        availability_stage="L0",
        publication_basis="하위 호환을 위해 race_no를 race_number alias로 함께 저장한다",
        publication_basis_refs=_SOURCE_SCHEMA_REFS,
        exception_rule="race_no와 동일한 값을 유지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="불변",
    ),
    _rule(
        field_path="race_info.response.body.items.item[]",
        field_role="source",
        source_api="API214_1",
        source_field="response.body.items.item[]",
        availability_stage="L0",
        publication_basis="출전표 원본 envelope 전체를 저장해 필드 인벤토리와 감사 근거로 사용한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원본 보존은 허용하지만 모델 입력 생성 시 사후 필드는 별도 차단 규칙을 적용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="array",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="collected_at",
        field_role="metadata",
        source_api="INTERNAL",
        source_field="collected_at",
        availability_stage="L0",
        publication_basis="수집 시각은 cutoff 감사와 재현성 검증에 필요하다",
        publication_basis_refs=_SOURCE_SCHEMA_REFS,
        exception_rule="snapshot 생성 당시의 수집 시각을 그대로 유지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="불변",
    ),
    _rule(
        field_path="status",
        field_role="metadata",
        source_api="INTERNAL",
        source_field="status",
        availability_stage="L0",
        publication_basis="수집 성공/실패 상태는 snapshot 품질 판단의 기본 메타데이터다",
        publication_basis_refs=_SOURCE_SCHEMA_REFS,
        exception_rule="정상 snapshot 판정은 status와 함께 읽는다",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="failed_horses[]",
        field_role="metadata",
        source_api="INTERNAL",
        source_field="failed_horses[]",
        availability_stage="L0",
        publication_basis="말 단위 soft-fail은 후속 재수집과 품질 진단에 필요하다",
        publication_basis_refs=_SOURCE_SCHEMA_REFS,
        exception_rule="예측 생성은 계속하되 실패한 말 목록을 감사 로그로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="array",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.rank",
        field_role="source",
        source_api="API72_2",
        source_field="rank",
        availability_stage="L-1",
        publication_basis="경주계획표에서 경주 등급을 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.budam",
        field_role="source",
        source_api="API72_2",
        source_field="budam",
        availability_stage="L-1",
        publication_basis="경주계획표에서 부담조건을 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.rc_dist",
        field_role="source",
        source_api="API72_2",
        source_field="rcDist",
        availability_stage="L-1",
        publication_basis="경주계획표에서 경주 거리를 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.age_cond",
        field_role="source",
        source_api="API72_2",
        source_field="ageCond",
        availability_stage="L-1",
        publication_basis="경주계획표에서 연령 조건을 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.sex_cond",
        field_role="source",
        source_api="API72_2",
        source_field="sexCond",
        availability_stage="L-1",
        publication_basis="경주계획표에서 성별 조건을 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.chaksun1",
        field_role="source",
        source_api="API72_2",
        source_field="chaksun1",
        availability_stage="L-1",
        publication_basis="경주계획표에서 1착 상금 구조를 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.chaksun2",
        field_role="source",
        source_api="API72_2",
        source_field="chaksun2",
        availability_stage="L-1",
        publication_basis="경주계획표에서 2착 상금 구조를 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.chaksun3",
        field_role="source",
        source_api="API72_2",
        source_field="chaksun3",
        availability_stage="L-1",
        publication_basis="경주계획표에서 3착 상금 구조를 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.chaksun4",
        field_role="source",
        source_api="API72_2",
        source_field="chaksun4",
        availability_stage="L-1",
        publication_basis="경주계획표에서 4착 상금 구조를 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_plan.chaksun5",
        field_role="source",
        source_api="API72_2",
        source_field="chaksun5",
        availability_stage="L-1",
        publication_basis="경주계획표에서 5착 상금 구조를 사전 제공한다",
        publication_basis_refs=(
            *_KRA_COLLECTION_REFS,
            "docs/prompts/data-go-kr-api-application.md",
        ),
        exception_rule="대상 rcNo와 일치하는 row만 채택",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="track.weather",
        field_role="source",
        source_api="API189_1",
        source_field="weather",
        availability_stage="L0 snapshot",
        publication_basis="날씨는 당일 변동 가능하므로 출전표 확정 시점 snapshot으로만 허용한다",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cutoff 이전 최초 정상 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="track.track",
        field_role="source",
        source_api="API189_1",
        source_field="track",
        availability_stage="L0 snapshot",
        publication_basis="주로 상태는 당일 변동 가능하므로 출전표 확정 시점 snapshot으로만 허용한다",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cutoff 이전 최초 정상 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="track.water_percent",
        field_role="source",
        source_api="API189_1",
        source_field="waterPercent",
        availability_stage="L0 snapshot",
        publication_basis="주로 수분율은 당일 변동 가능하므로 출전표 확정 시점 snapshot으로만 허용한다",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cutoff 이전 최초 정상 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="track.temperature",
        field_role="source",
        source_api="API189_1",
        source_field="temperature",
        availability_stage="L0 snapshot",
        publication_basis="기온은 당일 변동 가능하므로 출전표 확정 시점 snapshot으로만 허용한다",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cutoff 이전 최초 정상 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="track.humidity",
        field_role="source",
        source_api="API189_1",
        source_field="humidity",
        availability_stage="L0 snapshot",
        publication_basis="습도는 당일 변동 가능하므로 출전표 확정 시점 snapshot으로만 허용한다",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cutoff 이전 최초 정상 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="track.wind_direction",
        field_role="source",
        source_api="API189_1",
        source_field="windDirection",
        availability_stage="L0 snapshot",
        publication_basis="풍향은 당일 변동 가능하므로 출전표 확정 시점 snapshot으로만 허용한다",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cutoff 이전 최초 정상 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="track.wind_speed",
        field_role="source",
        source_api="API189_1",
        source_field="windSpeed",
        availability_stage="L0 snapshot",
        publication_basis="풍속은 당일 변동 가능하므로 출전표 확정 시점 snapshot으로만 허용한다",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cutoff 이전 최초 정상 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="cancelled_horses[]",
        field_role="source",
        source_api="API9_1",
        source_field="item[]",
        availability_stage="L0 snapshot",
        publication_basis="출전취소 정보는 pre-cutoff 최신 snapshot만 운영 사용 가능하다",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cutoff 이후 취소 정보로 기존 snapshot을 덮어쓰면 안 된다",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        value_type="array",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].chul_no",
        field_role="source",
        source_api="API214_1",
        source_field="chulNo",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 출전번호를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="말 배열 정렬과 예측 출력의 기준 키로 유지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].hr_no",
        field_role="source",
        source_api="API214_1",
        source_field="hrNo",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 말 식별자를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="문자열 식별자를 그대로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].hr_name",
        field_role="source",
        source_api="API214_1",
        source_field="hrName",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 말 이름을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 한글명을 그대로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].jk_no",
        field_role="source",
        source_api="API214_1",
        source_field="jkNo",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 기수 식별자를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="기수 상세/성적 API 조인 키로 재사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].jk_name",
        field_role="source",
        source_api="API214_1",
        source_field="jkName",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 기수 이름을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 이름을 그대로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].tr_no",
        field_role="source",
        source_api="API214_1",
        source_field="trNo",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 조교사 식별자를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="조교사 상세 API 조인 키로 재사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].tr_name",
        field_role="source",
        source_api="API214_1",
        source_field="trName",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 조교사 이름을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 이름을 그대로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].ow_no",
        field_role="source",
        source_api="API214_1",
        source_field="owNo",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 마주 식별자를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="마주 상세 API 조인 키로 재사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].ow_name",
        field_role="source",
        source_api="API214_1",
        source_field="owName",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 마주 이름을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 이름을 그대로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].age",
        field_role="source",
        source_api="API214_1",
        source_field="age",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 나이를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 숫자 값을 그대로 사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].sex",
        field_role="source",
        source_api="API214_1",
        source_field="sex",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 성별을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 문자열을 그대로 사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].name",
        field_role="source",
        source_api="API214_1",
        source_field="name",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 산지/국적 원문을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 문자열을 그대로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].country",
        field_role="derived",
        source_api="INTERNAL",
        source_field="normalize_prerace_horse_entry(name|country)",
        availability_stage="L0",
        publication_basis="출전표 기본 카드의 산지/국적 원문을 canonical country 필드로 정규화한다",
        publication_basis_refs=(
            "apps/api/utils/prerace_entry_normalizer.py",
            "docs/prerace-standard-field-catalog.md",
        ),
        exception_rule="name 또는 country alias가 비어 있으면 null로 저장하고 country_missing 플래그를 남긴다",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="불변",
    ),
    _rule(
        field_path="horses[].rank",
        field_role="source",
        source_api="API214_1",
        source_field="rank",
        availability_stage="L0",
        publication_basis="출전표 기본 카드의 rank는 결과 순위가 아니라 등급 문자열이다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="모델 입력 변환 단계에서는 class_rank로 rename해 결과 필드와 이름 충돌을 피한다",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].rating",
        field_role="source",
        source_api="API214_1",
        source_field="rating",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 레이팅을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 숫자 값을 그대로 사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].wg_budam",
        field_role="source",
        source_api="API214_1",
        source_field="wgBudam",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 부담중량을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 숫자 값을 그대로 사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].wg_budam_bigo",
        field_role="source",
        source_api="API214_1",
        source_field="wgBudamBigo",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 부담중량 비고를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 문자열을 그대로 사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].wg_hr",
        field_role="source",
        source_api="API214_1",
        source_field="wgHr",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 마체중 및 증감 원문을 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 문자열을 그대로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="필수",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].weight",
        field_role="derived",
        source_api="INTERNAL",
        source_field="parse_body_weight_from_wg_hr(wgHr)|weight",
        availability_stage="L0",
        publication_basis="출전표 기본 카드의 마체중 원문 또는 명시 weight 값을 정규화해 저장한다",
        publication_basis_refs=(
            "apps/api/utils/prerace_entry_normalizer.py",
            "docs/prerace-standard-field-catalog.md",
        ),
        exception_rule="허용 범위를 벗어나거나 파싱 실패하면 null로 저장하고 weight 관련 normalization_flags를 남긴다",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="불변",
    ),
    _rule(
        field_path="horses[].weight_delta",
        field_role="derived",
        source_api="INTERNAL",
        source_field="parse_weight_delta_from_wg_hr(wgHr)",
        availability_stage="L0",
        publication_basis="출전표 기본 카드의 마체중 증감 원문을 정수 증감치로 정규화한다",
        publication_basis_refs=(
            "apps/api/utils/prerace_entry_normalizer.py",
            "docs/prerace-standard-field-catalog.md",
        ),
        exception_rule="허용 범위를 벗어나거나 파싱 실패하면 null로 저장하고 weight_delta 관련 normalization_flags를 남긴다",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="불변",
    ),
    _rule(
        field_path="horses[].ilsu",
        field_role="source",
        source_api="API214_1",
        source_field="ilsu",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 휴양 일수 정보를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 숫자 값을 그대로 사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].hr_tool",
        field_role="source",
        source_api="API214_1",
        source_field="hrTool",
        availability_stage="L0",
        publication_basis="출전표 기본 카드에서 장구 정보를 직접 제공한다",
        publication_basis_refs=_ENTRY_CARD_REFS,
        exception_rule="원문 문자열을 그대로 보존",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].normalization_flags",
        field_role="derived",
        source_api="INTERNAL",
        source_field="normalize_prerace_horse_entry.flags",
        availability_stage="L0",
        publication_basis="정규화 단계에서 파싱 실패·결측·보정 여부를 audit용 플래그 목록으로 기록한다",
        publication_basis_refs=(
            "apps/api/utils/prerace_entry_normalizer.py",
            "docs/prerace-standard-field-catalog.md",
        ),
        exception_rule="정규화 단계에서 감지된 플래그를 중복 없이 정렬한 문자열 배열로 저장한다",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="선택",
        train_inference_flag="ALLOW",
        value_type="array",
        mutable_after_publish="불변",
    ),
)

FIELD_METADATA_RULES: tuple[FieldMetadataRule, ...] = (
    *EXACT_STANDARD_FIELD_RULES,
    _rule(
        field_path="race_plan.sch_st_time",
        field_role="source",
        source_api="API72_2",
        source_field="schStTime",
        availability_stage="L0 snapshot",
        publication_basis="경주계획표 예정 시각은 cutoff 이전 snapshot 고정값만 허용",
        publication_basis_refs=_HOLDOUT_REFS,
        exception_rule="cutoff 이전 최초 정상 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        path_aliases=("race_plan.schStTime",),
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="track",
        field_role="source",
        source_api="API189_1",
        source_field="*",
        availability_stage="L0 snapshot",
        publication_basis="주로/날씨는 출전표 확정 전후 변동 가능성이 있어 snapshot 기준을 사용",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="track.* 전체는 cutoff 이전 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        match_type="prefix",
        value_type="object",
        mutable_after_publish="가변",
        notes="track.weather, track.water_percent 등 하위 필드 전체를 포괄한다.",
    ),
    _rule(
        field_path="cancelled_horses",
        field_role="source",
        source_api="API9_1",
        source_field="item[]",
        availability_stage="L0 snapshot",
        publication_basis="출전취소 정보는 pre-cutoff 최신 snapshot만 운영 사용 가능",
        publication_basis_refs=(*_KRA_COLLECTION_REFS, *_HOLDOUT_REFS),
        exception_rule="cancelled_horses[] 전체는 cutoff 이전 snapshot만 허용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        match_type="prefix",
        value_type="array",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].training",
        field_role="source",
        source_api="API329",
        source_field="item[]",
        availability_stage="L0 snapshot",
        publication_basis="조교 현황은 cutoff 이전 snapshot이 남아 있을 때만 허용",
        publication_basis_refs=_KRA_COLLECTION_REFS,
        exception_rule="training 블록 및 파생치는 snapshot 고정값만 허용",
        validation_status="documented",
        validation_evidence=(*_RULEBOOK_REF, *_FEATURE_REFS),
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_SNAPSHOT_ONLY",
        match_type="prefix",
        value_type="object",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].hrDetail",
        field_role="source",
        source_api="API8_2",
        source_field="item",
        availability_stage="L-1",
        publication_basis="말 상세는 사전 정보지만 과거 재조회 시 최신 상태로 바뀔 수 있다",
        publication_basis_refs=_KRA_COLLECTION_REFS,
        exception_rule="당시 저장본만 허용하고 사후 재조회값은 금지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_STORED_ONLY",
        match_type="prefix",
        join_key="horses[].chul_no",
        value_type="object",
        mutable_after_publish="재조회 의존",
    ),
    _rule(
        field_path="horses[].jkDetail",
        field_role="source",
        source_api="API12_1",
        source_field="item",
        availability_stage="L-1",
        publication_basis="기수 상세는 사전 정보지만 과거 재조회 시 최신 상태로 바뀔 수 있다",
        publication_basis_refs=_KRA_COLLECTION_REFS,
        exception_rule="당시 저장본만 허용하고 사후 재조회값은 금지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_STORED_ONLY",
        match_type="prefix",
        join_key="horses[].chul_no",
        value_type="object",
        mutable_after_publish="재조회 의존",
    ),
    _rule(
        field_path="horses[].trDetail",
        field_role="source",
        source_api="API19_1",
        source_field="item",
        availability_stage="L-1",
        publication_basis="조교사 상세는 사전 정보지만 과거 재조회 시 최신 상태로 바뀔 수 있다",
        publication_basis_refs=_KRA_COLLECTION_REFS,
        exception_rule="당시 저장본만 허용하고 사후 재조회값은 금지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_STORED_ONLY",
        match_type="prefix",
        join_key="horses[].chul_no",
        value_type="object",
        mutable_after_publish="재조회 의존",
    ),
    _rule(
        field_path="horses[].jkStats",
        field_role="source",
        source_api="API11_1",
        source_field="item",
        availability_stage="L-1",
        publication_basis="기수 누적 통계는 사전 정보지만 재조회 오염 가능성이 있다",
        publication_basis_refs=_KRA_COLLECTION_REFS,
        exception_rule="당시 저장본만 허용하고 사후 재조회값은 금지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_STORED_ONLY",
        match_type="prefix",
        join_key="horses[].chul_no",
        value_type="object",
        mutable_after_publish="재조회 의존",
    ),
    _rule(
        field_path="horses[].owDetail",
        field_role="source",
        source_api="API14_1",
        source_field="item",
        availability_stage="L-1",
        publication_basis="마주 정보는 사전 정보지만 재조회 오염 가능성이 있다",
        publication_basis_refs=_KRA_COLLECTION_REFS,
        exception_rule="당시 저장본만 허용하고 사후 재조회값은 금지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_STORED_ONLY",
        match_type="prefix",
        join_key="horses[].chul_no",
        value_type="object",
        mutable_after_publish="재조회 의존",
    ),
    _rule(
        field_path="horses[].past_stats",
        field_role="derived",
        source_api="INTERNAL",
        source_field="db_client.get_past_top3_stats_for_race",
        availability_stage="L0",
        publication_basis="과거 경주 히스토리 파생은 기준 경주 이전 결과만 집계한다",
        publication_basis_refs=_FEATURE_REFS,
        exception_rule="현재 경주 결과를 참조하지 않고 당시 저장본 기준으로만 사용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="조건부 허용",
        train_inference_flag="ALLOW_STORED_ONLY",
        match_type="prefix",
        value_type="object",
        mutable_after_publish="불변",
    ),
    _rule(
        field_path="horses[].win_odds",
        field_role="source",
        source_api="API214_1",
        source_field="winOdds",
        availability_stage="?",
        publication_basis="출전표 기본 카드에 존재하지만 공개 시점 실측이 아직 끝나지 않았다",
        publication_basis_refs=_HOLDOUT_REFS,
        exception_rule="raw 저장과 연구는 허용하되 최종 운영 입력에서는 제외",
        validation_status="pending_measurement",
        validation_evidence=_RULEBOOK_REF,
        operational_status="보류",
        train_inference_flag="HOLD",
        path_aliases=("horses[].winOdds",),
        join_key="horses[].chul_no",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].plc_odds",
        field_role="source",
        source_api="API214_1",
        source_field="plcOdds",
        availability_stage="?",
        publication_basis="출전표 기본 카드에 존재하지만 공개 시점 실측이 아직 끝나지 않았다",
        publication_basis_refs=_HOLDOUT_REFS,
        exception_rule="raw 저장과 연구는 허용하되 최종 운영 입력에서는 제외",
        validation_status="pending_measurement",
        validation_evidence=_RULEBOOK_REF,
        operational_status="보류",
        train_inference_flag="HOLD",
        path_aliases=("horses[].plcOdds",),
        join_key="horses[].chul_no",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="horses[].computed_features.odds_rank",
        field_role="derived",
        source_api="INTERNAL",
        source_field="win_odds -> odds_rank",
        availability_stage="?",
        publication_basis="odds 의존 파생은 원천 공개 시점 검증이 끝나기 전까지 보류한다",
        publication_basis_refs=(*_HOLDOUT_REFS, *_FEATURE_REFS),
        exception_rule="win_odds/plc_odds 검증 완료 전까지 운영 입력 금지",
        validation_status="pending_measurement",
        validation_evidence=_RULEBOOK_REF,
        operational_status="보류",
        train_inference_flag="HOLD",
        value_type="scalar",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="race_odds",
        field_role="label",
        source_api="API160_1|API301",
        source_field="item[]",
        availability_stage="L+1",
        publication_basis="확정 배당은 결과 수집 경로에서만 적재된다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="배당 블록 전체는 입력 금지",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="prefix",
        value_type="object",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="ord",
        field_role="label",
        source_api="API214_1",
        source_field="ord",
        availability_stage="L+1",
        publication_basis="결과 착순은 결과 수집 후에만 의미가 생긴다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="ordBigo",
        field_role="label",
        source_api="API214_1",
        source_field="ordBigo",
        availability_stage="L+1",
        publication_basis="결과 비고는 결과 수집 후에만 의미가 생긴다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="rankRise",
        field_role="label",
        source_api="API214_1",
        source_field="rankRise",
        availability_stage="L+1",
        publication_basis="결과 기반 순위 변동은 결과 수집 후에만 의미가 생긴다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="diffUnit",
        field_role="label",
        source_api="API214_1",
        source_field="diffUnit",
        availability_stage="L+1",
        publication_basis="도착 차는 결과 수집 후에만 의미가 생긴다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="rcTime",
        field_role="label",
        source_api="API214_1",
        source_field="rcTime",
        availability_stage="L+1",
        publication_basis="기록은 결과 수집 후에만 의미가 생긴다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="result",
        field_role="label",
        source_api="API214_1",
        source_field="result",
        availability_stage="L+1",
        publication_basis="결과 상태 필드는 결과 수집 후에만 의미가 생긴다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="resultTime",
        field_role="label",
        source_api="API214_1",
        source_field="resultTime",
        availability_stage="L+1",
        publication_basis="결과 기록 필드는 결과 수집 후에만 의미가 생긴다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="finish_position",
        field_role="label",
        source_api="API214_1",
        source_field="finish_position",
        availability_stage="L+1",
        publication_basis="결승 순위 필드는 결과 수집 후에만 의미가 생긴다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="dividend",
        field_role="label",
        source_api="API160_1|API301",
        source_field="dividend",
        availability_stage="L+1",
        publication_basis="확정 배당금은 결과 수집 경로에서만 적재된다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="payout",
        field_role="label",
        source_api="API160_1|API301",
        source_field="payout",
        availability_stage="L+1",
        publication_basis="환급금은 결과 수집 경로에서만 적재된다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="leaf key 기준 전역 차단",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="금지",
        train_inference_flag="BLOCK",
        match_type="leaf",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="top3",
        field_role="label",
        source_api="INTERNAL",
        source_field="result_data.top3",
        availability_stage="L+1",
        publication_basis="정답 라벨은 결과 확정 후 내부적으로만 계산된다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="정답/평가 전용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="라벨 전용",
        train_inference_flag="LABEL_ONLY",
        value_type="array",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="is_top3",
        field_role="label",
        source_api="INTERNAL",
        source_field="result_data.top3 -> membership",
        availability_stage="L+1",
        publication_basis="정답 라벨은 결과 확정 후 내부적으로만 계산된다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="정답/평가 전용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="라벨 전용",
        train_inference_flag="LABEL_ONLY",
        value_type="scalar",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="actual_result",
        field_role="label",
        source_api="INTERNAL",
        source_field="result_data",
        availability_stage="L+1",
        publication_basis="정답 라벨은 결과 확정 후 내부적으로만 계산된다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="정답/평가 전용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="라벨 전용",
        train_inference_flag="LABEL_ONLY",
        value_type="object",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="result_data",
        field_role="label",
        source_api="INTERNAL",
        source_field="result_data.*",
        availability_stage="L+1",
        publication_basis="결과 블록은 결과 수집 후에만 완성된다",
        publication_basis_refs=_POST_RACE_REFS,
        exception_rule="결과 블록 전체는 라벨/평가 전용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="라벨 전용",
        train_inference_flag="LABEL_ONLY",
        match_type="prefix",
        value_type="object",
        mutable_after_publish="사후 전용",
    ),
    _rule(
        field_path="snapshot_meta",
        field_role="metadata",
        source_api="INTERNAL",
        source_field="snapshot_meta.*",
        availability_stage="L0",
        publication_basis="홀드아웃 재생과 운영 감사용 내부 메타데이터",
        publication_basis_refs=(
            "packages/scripts/autoresearch/prepare.py",
            "packages/scripts/autoresearch/holdout_split.py",
        ),
        exception_rule="감사/운영 메타데이터 전용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="메타 전용",
        train_inference_flag="META_ONLY",
        match_type="prefix",
        value_type="object",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="field_policy",
        field_role="metadata",
        source_api="INTERNAL",
        source_field="field_policy.*",
        availability_stage="L0",
        publication_basis="필드 필터링 리포트는 감사/운영 메타데이터다",
        publication_basis_refs=("packages/scripts/shared/prerace_field_policy.py",),
        exception_rule="감사/운영 메타데이터 전용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="메타 전용",
        train_inference_flag="META_ONLY",
        match_type="prefix",
        value_type="object",
        mutable_after_publish="가변",
    ),
    _rule(
        field_path="source_field_tags",
        field_role="metadata",
        source_api="INTERNAL",
        source_field="source_field_tags.*",
        availability_stage="L0",
        publication_basis="수집 단계 원천 필드 태깅은 감사와 누수 점검용 메타데이터다",
        publication_basis_refs=("apps/api/services/prerace_field_tagging.py",),
        exception_rule="감사/운영 메타데이터 전용",
        validation_status="documented",
        validation_evidence=_RULEBOOK_REF,
        operational_status="메타 전용",
        train_inference_flag="META_ONLY",
        match_type="prefix",
        value_type="object",
        mutable_after_publish="가변",
    ),
)


def canonical_field_metadata_rows() -> tuple[dict[str, str], ...]:
    """정규 CSV에 기록할 메타데이터 규칙 행들을 반환한다."""

    return tuple(rule.to_csv_row() for rule in FIELD_METADATA_RULES)


def match_field_metadata_rule(path: str) -> FieldMetadataRule | None:
    """런타임 payload 경로에 대응하는 중앙 메타데이터 규칙을 찾는다."""

    normalized_path = normalize_field_path(path)
    leaf_key = normalized_path.rsplit(".", 1)[-1]

    for rule in FIELD_METADATA_RULES:
        if rule.match_type != "exact":
            continue
        if normalized_path in rule.normalized_patterns():
            return rule

    for rule in FIELD_METADATA_RULES:
        if rule.match_type != "prefix":
            continue
        for pattern in rule.normalized_patterns():
            if (
                normalized_path == pattern
                or normalized_path.startswith(f"{pattern}.")
                or normalized_path.startswith(f"{pattern}[")
            ):
                return rule

    for rule in FIELD_METADATA_RULES:
        if rule.match_type != "leaf":
            continue
        if leaf_key in rule.normalized_patterns():
            return rule

    return None
