# 프로덕션 환경용 docker-compose 오버라이드
version: '3.8'

services:
  api:
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - DEBUG=false
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  celery-worker:
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    command: celery -A infrastructure.celery_app worker --loglevel=info --concurrency=8
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: kra-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - kra-network
    restart: unless-stopped

  # 프로덕션에서는 pgAdmin 제외
  pgadmin:
    profiles:
      - never