name: NodeJS Collector API Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/collector/**'
      - '.github/workflows/collector-test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/collector/**'
      - '.github/workflows/collector-test.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test API Endpoints
    runs-on: ubuntu-latest
    env:
      KRA_SERVICE_KEY: ${{ secrets.KRA_SERVICE_KEY }}
    
    defaults:
      run:
        working-directory: apps/collector
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Install dependencies (workspace)
      working-directory: .
      run: pnpm -w -F @apps/collector install --no-frozen-lockfile
    
    - name: Run lint
      working-directory: .
      run: pnpm -F @apps/collector run lint
      
    - name: Run type check
      working-directory: .
      run: pnpm -F @apps/collector run typecheck
    
    - name: Run unit tests (CI subset)
      working-directory: .
      run: pnpm -F @apps/collector run test:ci
      env:
        NODE_ENV: test
        LOG_LEVEL: error
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      with:
        directory: ./apps/collector/coverage
        flags: collector
    
    - name: Start server for E2E tests
      working-directory: .
      run: |
        pnpm -F @apps/collector run build
        pnpm -F @apps/collector start &
        sleep 5
      env:
        NODE_ENV: test
        PORT: 3001
        LOG_LEVEL: error
    
    - name: Run E2E API tests
      if: ${{ env.KRA_SERVICE_KEY != '' }}
      working-directory: .
      run: pnpm -F @apps/collector run test:kra
    
    - name: Check API health
      run: |
        # Health endpoint should return 200 OK
        curl -fsS http://localhost:3001/health > /dev/null
    
    - name: Test critical endpoints
      if: ${{ env.KRA_SERVICE_KEY != '' }}
      run: |
        # Test Race API
        curl -f "http://localhost:3001/api/v1/races/20240106/서울/1" || exit 1
        
        # Test Horse API  
        curl -f "http://localhost:3001/api/v1/horses/0053587" || exit 1
        
        # Test Jockey API
        curl -f "http://localhost:3001/api/v1/jockeys/080476" || exit 1
        
        # Test Trainer API
        curl -f "http://localhost:3001/api/v1/trainers/070165" || exit 1
    
    - name: Stop server
      if: always()
      run: pkill -f "node" || true
